### ISSUE TITLE
React 16 upgrade

### ISSUE THREAD

**Issue by cjies** [iCHEF/gypcrete#81]
## Before upgrade react

- [x] Upgrade **storybook** dependencies to [v3.2.11](https://github.com/storybooks/storybook/releases/tag/v3.2.11) or above. (#93)
- [x] Upgrade **enzyme** to [v3](https://github.com/airbnb/enzyme/blob/master/CHANGELOG.md#300). (#183)
  * React dependencies was removed in enzyme v3, use new `Adapters` system to import React library that we used, check the [migration guide](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#configuring-your-adapter) here.
- [x] Upgrade **webpack**  and `extract-text-webpack-plugin` to v3 (#101)
- [x] Upgrade **Babel** to v7 (#185)
- [x] Upgrade **ESlint** v5 (#186)

## React API changes

- [x] Upgrade **react**, **react-dom**, **react-test-renderer** to v16. (#187)
- [x] As #79, Migrate `unstable_renderSubtreeIntoContainer` to `ReactDOM.createPortal()`. (#188)
- [x] Get rid of `ReactDOM.findDOMNode()` as it's [being deprecated](https://reactjs.org/blog/2018/10/23/react-v-16-6.html) under strict mode in React 16.6. (#189)

**Comment by cjies** [comment]
## Optional upgrade

- Upgrade **babel** and related presets and plugins to latest.
- Upgrade **autoprefixer** to v7.
- Upgrade **flow** and **eslint-plugin-react** to latest
  * From flow v0.53 or above, there have some major changes to Flow's model for react. (Check [Flow v0.53 changelog](https://github.com/facebook/flow/releases/tag/v0.53.0) and yannickcr/eslint-plugin-react#1376)

**Comment by zhusee2** [comment]
About Flow: I'm considering to change to TypeScript.
In all TypeScript seems to be more active in development, it supports JSX mode, and the type check works better in, you know, the VScode editor.

**Comment by zhusee2** [comment]
Was trying to upgrade to Lerna v3, but it relies really heavily on **annotated tags** and that cause more issues than v2 in our workflow scenario.

This PR seems to solve the issue we're currently encountering:
https://github.com/lerna/lerna/pull/1712

**Comment by cjies** [comment]
Is that any conflict between lerna upgrade and react upgrade?
I think both are not associated to each other.

**Comment by zhusee2** [comment]
No, they're not really relevant.
So we're staying in Lerna 2 for now. XD

**Comment by zhusee2** [comment]
I believe it's about time to call it done.
Thanks for everyone who participates in this!
